backend/config/routes.rb
Rails.application.routes.draw do
  resources :thoughts, only: [:index, :show, :create]
  resources :messages, only: [:index, :show, :create]
  resources :convos, only: [:index, :show, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

backend/app/models/convo.rb
class Convo < ApplicationRecord
  has_many :messages
  has_many :thoughts, through: :messages
end

backend/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :convo
  has_many :thoughts
end

backend/app/models/thought.rb
class Thought < ApplicationRecord
  belongs_to :message
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

backend/app/controllers/convos_controller.rb
class ConvosController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:create]
  before_action :set_convo, only: [:show, :edit, :update, :destroy]

  # GET /convos
  # GET /convos.json
  def index
    @convos = Convo.all
    render json: @convos
  end

  # GET /convos/1
  # GET /convos/1.json
  def show
    @convo = Convo.find_by(id: params[:id])
    render json: @convo
  end

  # GET /convos/new
  def new
    @convo = Convo.new
  end

  # GET /convos/1/edit
  def edit
  end

  # POST /convos
  # POST /convos.json
  def create
    @convo = Convo.create(title: params[:title])

    if @convo.valid?
      render json: @convo
    else
      render json: { errors: @convo.errors.full_messages }, status: 400
    end
  end

  # PATCH/PUT /convos/1
  # PATCH/PUT /convos/1.json
  def update
    respond_to do |format|
      if @convo.update(convo_params)
        format.html { redirect_to @convo, notice: 'Convo was successfully updated.' }
        format.json { render :show, status: :ok, location: @convo }
      else
        format.html { render :edit }
        format.json { render json: @convo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /convos/1
  # DELETE /convos/1.json
  def destroy
    @convo.destroy
    respond_to do |format|
      format.html { redirect_to convos_url, notice: 'Convo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_convo
      @convo = Convo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def convo_params
      params.require(:convo).permit(:title)
    end
end

backend/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:create]
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
    render json: @messages
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find_by(id: params[:id])
    render json: @message
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.create(
      text: params[:text],
      convo_id: params[:convo_id]
    )

    if @message.valid?
      render json: @message
    else
      render json: { errors: @message.errors.full_messages }, status: 400
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:text)
    end
end

backend/app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:create]
  before_action :set_thought, only: [:show, :edit, :update, :destroy]

  # GET /thoughts
  # GET /thoughts.json
  def index
    @thoughts = Thought.all
    render json: @thoughts
  end

  # GET /thoughts/1
  # GET /thoughts/1.json
  def show
    @thought = Thought.find_by(id: params[:id])
    render json: @thought
  end

  # GET /thoughts/new
  def new
    @thought = Thought.new
  end

  # GET /thoughts/1/edit
  def edit
  end

  # POST /thoughts
  # POST /thoughts.json
  def create
    @thought = Thought.create(
      text: params[:text],
      message_id: params[:message_id]
    )

    if @thought.valid?
      render json: @thought
    else
      render json: { errors: @thought.errors.full_messages }, status: 400
    end
  end

  # PATCH/PUT /thoughts/1
  # PATCH/PUT /thoughts/1.json
  def update
    respond_to do |format|
      if @thought.update(thought_params)
        format.html { redirect_to @thought, notice: 'Thought was successfully updated.' }
        format.json { render :show, status: :ok, location: @thought }
      else
        format.html { render :edit }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thoughts/1
  # DELETE /thoughts/1.json
  def destroy
    @thought.destroy
    respond_to do |format|
      format.html { redirect_to thoughts_url, notice: 'Thought was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thought
      @thought = Thought.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def thought_params
      params.require(:thought).permit(:text)
    end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/convos_helper.rb
module ConvosHelper
end

backend/app/helpers/messages_helper.rb
module MessagesHelper
end

backend/app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

backend/app/views/convos/_form.html.erb
<%= form_with(model: convo, local: true) do |form| %>
  <% if convo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(convo.errors.count, "error") %> prohibited this convo from being saved:</h2>

      <ul>
        <% convo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/convos/edit.html.erb
<h1>Editing Convo</h1>

<%= render 'form', convo: @convo %>

<%= link_to 'Show', @convo %> |
<%= link_to 'Back', convos_path %>

backend/app/views/convos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Convos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @convos.each do |convo| %>
      <tr>
        <td><%= convo.title %></td>
        <td><%= link_to 'Show', convo %></td>
        <td><%= link_to 'Edit', edit_convo_path(convo) %></td>
        <td><%= link_to 'Destroy', convo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Convo', new_convo_path %>

backend/app/views/convos/new.html.erb
<h1>New Convo</h1>

<%= render 'form', convo: @convo %>

<%= link_to 'Back', convos_path %>

backend/app/views/convos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @convo.title %>
</p>

<%= link_to 'Edit', edit_convo_path(@convo) %> |
<%= link_to 'Back', convos_path %>

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

backend/app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

backend/app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.text %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

backend/app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

backend/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @message.text %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

backend/app/views/thoughts/_form.html.erb
<%= form_with(model: thought, local: true) do |form| %>
  <% if thought.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thought.errors.count, "error") %> prohibited this thought from being saved:</h2>

      <ul>
        <% thought.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/thoughts/edit.html.erb
<h1>Editing Thought</h1>

<%= render 'form', thought: @thought %>

<%= link_to 'Show', @thought %> |
<%= link_to 'Back', thoughts_path %>

backend/app/views/thoughts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Thoughts</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thoughts.each do |thought| %>
      <tr>
        <td><%= thought.text %></td>
        <td><%= link_to 'Show', thought %></td>
        <td><%= link_to 'Edit', edit_thought_path(thought) %></td>
        <td><%= link_to 'Destroy', thought, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thought', new_thought_path %>

backend/app/views/thoughts/new.html.erb
<h1>New Thought</h1>

<%= render 'form', thought: @thought %>

<%= link_to 'Back', thoughts_path %>

backend/app/views/thoughts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @thought.text %>
</p>

<%= link_to 'Edit', edit_thought_path(@thought) %> |
<%= link_to 'Back', thoughts_path %>